# Generated by Django 5.2.14 on 2026-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('subscriber', 'Subscritor'), ('subscriber_pro', 'Subscritor Pro')], default='subscriber', max_length=20),
        ),
    ]
