# Generated by Codex on 2026-06-15

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamticketpurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='streamticketpurchase',
            name='artist_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='streamticketpurchase',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='streamticketpurchase',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='streamticketpurchase',
            name='stripe_connected_account_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='streamticketpurchase',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_connected_account_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
