# Generated by Django 5.2.14 on 2026-06-17 09:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_artist_contact_email_artist_contact_phone'),
        ('payments', '0003_connect_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGalleryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=120)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=120)),
                ('stripe_connected_account_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('artist_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery_purchases', to='accounts.fan')),
            ],
        ),
    ]
