# Generated by Django 5.2.14 on 2026-06-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_photogallerypurchase'),
        ('streams', '0011_photogallery_photogalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallerypurchase',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='streams.photogallery'),
        ),
        migrations.AlterUniqueTogether(
            name='photogallerypurchase',
            unique_together={('fan', 'gallery')},
        ),
    ]
