# Generated by Django 5.2.14 on 2026-06-18 13:17

from django.db import migrations, models


def backfill_purchase_livemode(apps, schema_editor):
    StreamTicketPurchase = apps.get_model('payments', 'StreamTicketPurchase')
    PhotoGalleryPurchase = apps.get_model('payments', 'PhotoGalleryPurchase')
    StreamTicketPurchase.objects.filter(stripe_session_id__startswith='cs_live_').update(stripe_livemode=True)
    StreamTicketPurchase.objects.filter(stripe_session_id__startswith='cs_test_').update(stripe_livemode=False)
    PhotoGalleryPurchase.objects.filter(stripe_session_id__startswith='cs_live_').update(stripe_livemode=True)
    PhotoGalleryPurchase.objects.filter(stripe_session_id__startswith='cs_test_').update(stripe_livemode=False)


def reverse_backfill_purchase_livemode(apps, schema_editor):
    StreamTicketPurchase = apps.get_model('payments', 'StreamTicketPurchase')
    PhotoGalleryPurchase = apps.get_model('payments', 'PhotoGalleryPurchase')
    Subscription = apps.get_model('payments', 'Subscription')
    StreamTicketPurchase.objects.update(stripe_livemode=False)
    PhotoGalleryPurchase.objects.update(stripe_livemode=False)
    Subscription.objects.update(stripe_livemode=False)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_photogallerypurchase_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallerypurchase',
            name='stripe_livemode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamticketpurchase',
            name='stripe_livemode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_livemode',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_purchase_livemode, reverse_backfill_purchase_livemode),
    ]
