# Generated by Django 5.2.14 on 2026-06-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artists/gallery/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='accounts.artist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
