# Generated by Django 5.2.14 on 2026-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_artistphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='StageLink', max_length=80)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('background_overlay', models.PositiveSmallIntegerField(default=75)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aparencia do site',
                'verbose_name_plural': 'Aparencia do site',
            },
        ),
    ]
