# Generated by Django 5.2.14 on 2026-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_siteappearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fans/'),
        ),
        migrations.AddField(
            model_name='fan',
            name='social_avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
