# Generated by Django 5.2.14 on 2026-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fan_photo_fan_social_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
