# Generated by Django 5.2.14 on 2026-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_siteappearance_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='headline',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='artist',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/heroes/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='website_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recomendado: PNG transparente horizontal, cerca de 600x180 px.', null=True, upload_to='site/'),
        ),
    ]
