# Generated by Django 5.2.14 on 2026-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_artist_user_organization_artist_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('musician', 'Músico'), ('fan', 'Fã'), ('manager', 'Manager / equipa')], max_length=20),
        ),
    ]
