# Generated by Django 5.2.14 on 2026-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='fans_who_favorited', to='accounts.artist'),
        ),
    ]
