# Generated by Django 5.2.14 on 2026-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fan_favorite_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('musician', 'Músico'), ('fan', 'Público'), ('manager', 'Manager / equipa')], max_length=20),
        ),
    ]
