# Generated by Django 5.2.14 on 2026-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('musician', 'Artista'), ('fan', 'Público'), ('manager', 'Manager / equipa')], max_length=20),
        ),
    ]
