# Generated by Django 5.2.14 on 2026-06-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('interest_type', models.CharField(choices=[('fan', 'Fã'), ('artist', 'Artista'), ('both', 'Ambos')], default='fan', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscritor da newsletter',
                'verbose_name_plural': 'Subscritores da newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
