# Generated by Django 5.2.14 on 2026-06-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cloudflare_live_input_uid',
            field=models.CharField(blank=True, help_text='Live Input UID principal do artista no Cloudflare Stream.', max_length=120),
        ),
    ]
