# Generated by Django 5.2.14 on 2026-06-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_artist_cloudflare_live_input_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cloudflare_rtmps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='cloudflare_stream_key',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
