# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_artist_cloudflare_rtmps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='ID da conta Stripe Connect do artista.', max_length=120),
        ),
        migrations.AddField(
            model_name='artist',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
