# Generated by Django 5.2.14 on 2026-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_artist_stripe_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='artist',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
