# Generated by Django 5.2.14 on 2026-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_artist_contact_email_artist_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('musician', 'Artista'), ('fan', 'Público')], max_length=20),
        ),
    ]
