# Generated by Django 5.2.14 on 2026-06-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('contact_type', models.CharField(choices=[('general', 'Geral'), ('finance', 'Financeiro'), ('technical', 'Tecnico')], max_length=20)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_review', 'Em analise'), ('resolved', 'Resolvido')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem de contacto',
                'verbose_name_plural': 'Mensagens de contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
