# Generated by Django 5.2.14 on 2026-06-20 17:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percentagem da comissao StageHub aplicada as vendas deste artista.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
