# Generated by Django 5.2.14 on 2026-06-22 13:11

from django.db import migrations, models


def set_mode_for_artists_with_active_subscriptions(apps, schema_editor):
    Artist = apps.get_model('accounts', 'Artist')
    Subscription = apps.get_model('payments', 'Subscription')
    active_artist_ids = Subscription.objects.filter(status='active').values_list('artist_id', flat=True).distinct()
    Artist.objects.filter(id__in=active_artist_ids).update(monetization_mode='subscription_paid_exclusive')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_artist_commission_rate'),
        ('payments', '0006_photogallerypurchase_stripe_livemode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='monetization_mode',
            field=models.CharField(choices=[('subscription_only', 'Somente subscricao'), ('subscription_paid_exclusive', 'Subscricao e material pago exclusivo'), ('paid_content_only', 'Somente material pago')], default='paid_content_only', help_text='Define se o artista usa subscricao, material pago exclusivo para subscritores ou material pago aberto a todos.', max_length=40),
        ),
        migrations.RunPython(set_mode_for_artists_with_active_subscriptions, migrations.RunPython.noop),
    ]
