# Generated by Django 5.2.14 on 2026-06-26 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_artist_monetization_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('request', 'Pedido'), ('login', 'Login'), ('logout', 'Logout'), ('admin', 'Admin'), ('payment', 'Pagamento'), ('upload', 'Upload'), ('error', 'Erro')], default='request', max_length=20)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_string', models.CharField(blank=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('view_name', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade do site',
                'verbose_name_plural': 'Atividade do site',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_ac_created_91b66e_idx'), models.Index(fields=['action', '-created_at'], name='accounts_ac_action_2bf4c4_idx'), models.Index(fields=['status_code', '-created_at'], name='accounts_ac_status__13f07c_idx'), models.Index(fields=['user', '-created_at'], name='accounts_ac_user_id_3418de_idx'), models.Index(fields=['path'], name='accounts_ac_path_d3e4d2_idx')],
            },
        ),
    ]
