# Generated by Django 5.2.14 on 2026-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_institutional',
            field=models.BooleanField(default=False, help_text='Permite ao artista disponibilizar conteúdos gratuitos individualmente.'),
        ),
    ]
