# Generated by Django 5.2.14 on 2026-06-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='streams/covers/'),
        ),
    ]
