# Generated by Django 5.2.14 on 2026-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_livestream_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='youtube_video_id',
            field=models.CharField(max_length=200),
        ),
    ]
