# Generated by Django 5.2.14 on 2026-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_alter_livestream_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='event_type',
            field=models.CharField(choices=[('live', 'Ao vivo'), ('premiere', 'Estreia'), ('recorded', 'Vídeo gravado'), ('replay', 'Replay')], default='live', max_length=20),
        ),
    ]
