# Generated by Django 5.2.14 on 2026-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_livestream_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
