# Generated by Django 5.2.14 on 2026-06-10 15:28

from django.db import migrations, models


def keep_existing_youtube_events(apps, schema_editor):
    LiveStream = apps.get_model('streams', 'LiveStream')
    LiveStream.objects.exclude(youtube_video_id='').update(video_provider='youtube')


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_livestream_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='cloudflare_live_input_uid',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='livestream',
            name='cloudflare_playback_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='cloudflare_video_uid',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='livestream',
            name='video_provider',
            field=models.CharField(choices=[('cloudflare_stream', 'Cloudflare Stream'), ('cloudflare_webrtc', 'Cloudflare WebRTC'), ('youtube', 'YouTube legado')], default='cloudflare_stream', max_length=30),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(keep_existing_youtube_events, migrations.RunPython.noop),
    ]
