# Generated by Django 5.2.14 on 2026-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_livestream_cloudflare_live_input_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duração estimada em minutos (opcional)', null=True),
        ),
    ]
