# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_livestream_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='cloudflare_upload_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='cloudflare_upload_status',
            field=models.CharField(
                choices=[
                    ('not_requested', 'Sem upload direto'),
                    ('pending', 'Upload pendente'),
                    ('uploaded', 'Upload enviado'),
                ],
                default='not_requested',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='livestream',
            name='cloudflare_upload_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='livestream',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
