# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_livestream_direct_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='artist_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tip',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tip',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tip',
            name='stripe_connected_account_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
