# Generated by Django 5.2.14 on 2026-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0009_tip_connect_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='video_provider',
            field=models.CharField(choices=[('cloudflare_stream', 'Video StageHub'), ('cloudflare_webrtc', 'Direto StageHub experimental')], default='cloudflare_stream', max_length=30),
        ),
    ]
