# Generated by Django 5.2.14 on 2026-06-17 09:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_artist_contact_email_artist_contact_phone'),
        ('streams', '0010_alter_livestream_video_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('public_cover', models.ImageField(upload_to='photo_galleries/covers/')),
                ('access_price', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente de validacao'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('suspended', 'Suspensa')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_galleries', to='accounts.artist')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_photo_galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_galleries/private/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='streams.photogallery')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
