# Generated by Django 5.2.14 on 2026-06-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0012_sync_photo_gallery_publication_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='stripe_livemode',
            field=models.BooleanField(default=False),
        ),
    ]
