# Generated by Django 5.2.14 on 2026-06-20 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0013_tip_stripe_livemode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('cloudflare_id', models.CharField(max_length=160)),
                ('action', models.CharField(choices=[('delete_one', 'Apagar ficheiro'), ('delete_selected', 'Apagar selecionados'), ('delete_user', 'Apagar por utilizador'), ('delete_event', 'Apagar por evento'), ('delete_orphan', 'Apagar orfao'), ('delete_removed', 'Apagar marcados como removidos')], max_length=40)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de eliminacao de media',
                'verbose_name_plural': 'Logs de eliminacao de media',
                'ordering': ['-created_at'],
            },
        ),
    ]
