# Generated by Django 5.2.14 on 2026-06-24 17:02

from decimal import Decimal
from django.db import migrations, models


def set_minimum_stream_price(apps, schema_editor):
    LiveStream = apps.get_model('streams', 'LiveStream')
    LiveStream.objects.filter(access_price__lt=Decimal('2.00')).update(access_price=Decimal('2.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0014_mediadeletionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='access_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=8),
        ),
        migrations.RunPython(set_minimum_stream_price, migrations.RunPython.noop),
    ]
