# Generated by Django 5.2.14 on 2026-07-02 08:59

from django.db import migrations, models


def classify_existing_subscription_content(apps, schema_editor):
    LiveStream = apps.get_model('streams', 'LiveStream')
    PhotoGallery = apps.get_model('streams', 'PhotoGallery')
    subscription_filter = {'artist__monetization_mode': 'subscription_only'}
    LiveStream.objects.filter(**subscription_filter).update(access_type='subscribers')
    PhotoGallery.objects.filter(**subscription_filter).update(access_type='subscribers')


def restore_existing_content_to_paid(apps, schema_editor):
    apps.get_model('streams', 'LiveStream').objects.update(access_type='paid')
    apps.get_model('streams', 'PhotoGallery').objects.update(access_type='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0015_alter_livestream_access_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='access_type',
            field=models.CharField(choices=[('paid', 'Pago'), ('free', 'Gratuito'), ('subscribers', 'Apenas subscritores')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='access_type',
            field=models.CharField(choices=[('paid', 'Pago'), ('free', 'Gratuito'), ('subscribers', 'Apenas subscritores')], default='paid', max_length=20),
        ),
        migrations.RunPython(
            classify_existing_subscription_content,
            restore_existing_content_to_paid,
        ),
    ]
